---
title: "PIBIC - Detecção e avaliação de viés de aprendizado de máquina utilizando
  o Censo Demográfico"
author: "Ana Beatriz Parra Ferreira"
date: "2024-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache.lazy = FALSE) 
setwd("C:/Users/anapa/Iniciação científica/git")
```

```{r bibliotecas}
# install.packages("censobr")  #instalar biblioteca do censo
library(censobr)
library(tidyverse)

```

## Download e leitura dos dados do Censo

```{r lendo}
#definindo variáveis
colunas = c('code_muni','abbrev_state', 'V0002', 'V0601', 'V6036', 'V0606','V6400','V6525','V6930')

pop <- read_population(
  year = 2010,          # year of reference
  columns = colunas,       # select columns to read
  add_labels = 'pt',    # add labels to categorical variables
  as_data_frame = TRUE, # return an Arrow DataSet se FALSE, data.frame se TRUE
  showProgress = TRUE,  # show download progress bar
  cache = TRUE       # cache data for faster access later
  )
# censobr::censobr_cache(delete_file = "C:/Users/anapa/AppData/Local/R/cache/R/censobr/data_release_v0.3.0/2010_population_v0.3.0.parquet")

```
<!-- --------------------------- -->
<!-- FileSystemDataset (query) -->
<!-- code_muni: int32 -->
<!-- abbrev_state: string -->
<!-- V0002: string -->
<!-- V0601: string (case_when({1=(V0601 == "1"), 2=(V0601 == "2"), 3=(V0601 == "9")}, "Masculino", "Feminino", "Ignorado")) -->
<!-- V6036: double -->
<!-- V0606: string (case_when({1=(V0606 == "1"), 2=(V0606 == "2"), 3=(V0606 == "3"), 4=(V0606 == "4"), 5=(V0606 == "5"), 6=(V0606 == "9")}, "Branca", "Preta", "Amarela", "Parda", "Indígena", "Ignorado")) -->
<!-- V6400: string (case_when({1=(V6400 == "1"), 2=(V6400 == "2"), 3=(V6400 == "3"), 4=(V6400 == "4")}, "Sem instrução e fundamental incompleto", "Fundamental completo e médio incompleto", "Médio completo e superior incompleto", "Superior completo")) -->
<!-- V6525: double -->
<!-- V6930: string (case_when({1=(V6930 == "1"), 2=(V6930 == "2"), 3=(V6930 == "3"), 4=(V6930 == "4"), 5=(V6930 == "5"), 6=(V6930 == "6"), 7=(V6930 == "7")}, "Empregados com carteira de trabalho assinada", "Militares e funcionários públicos estatutários", "Empregados sem carteira de trabalho assinada", "Conta própria", "Empregadores", "Não remunerados", "Trabalhadores na produção para o próprio consumo")) -->

<!-- See $.data for the source Arrow object -->



```{r}
# dados <- pop |> 
#   mutate(
#     V0601 = case_when(
#       V0601 == "1" ~ "Masculino",
#       V0601 == "2" ~ "Feminino",
#       V0601 == "9" ~ "Ignorado",
#       TRUE ~ "Desconhecido"
#     ),
#     V0606 = case_when(
#       V0606 == "1" ~ "Branca",
#       V0606 == "2" ~ "Preta",
#       V0606 == "3" ~ "Amarela",
#       V0606 == "4" ~ "Parda",
#       V0606 == "5" ~ "Indígena",
#       V0606 == "9" ~ "Ignorado",
#       TRUE ~ "Desconhecido"
#     ),
#     V6400 = case_when(
#       V6400 == "1" ~ "Sem instrução e fundamental incompleto",
#       V6400 == "2" ~ "Fundamental completo e médio incompleto",
#       V6400 == "3" ~ "Médio completo e superior incompleto",
#       V6400 == "4" ~ "Superior completo",
#       TRUE ~ "Desconhecido"
#     ),
#     V6930 = case_when(
#       V6930 == "1" ~ "Empregados com carteira de trabalho assinada",
#       V6930 == "2" ~ "Militares e funcionários públicos estatutários",
#       V6930 == "3" ~ "Empregados sem carteira de trabalho assinada",
#       V6930 == "4" ~ "Conta própria",
#       V6930 == "5" ~ "Empregadores",
#       V6930 == "6" ~ "Não remunerados",
#       V6930 == "7" ~ "Trabalhadores na produção para o próprio consumo",
#       TRUE ~ "Desconhecido"
#     )
#   )
```

Renomeando as variáveis e filtrando valores não nulos de rendimento total 

```{r renomeando,  results='hide'}
dados <- pop |> 
  rename(sexo = V0002, idade = V6036, cor_raca = V0606, nivel_instrucao = V6400, 
         rendimento = V6525, ocupacao_emprego = V6930) |> 
  filter(rendimento != is.na(rendimento))

head(pop)
```
Download do dataframe

```{r  baixando}
write_csv(dados, "dados/censo.csv") 
```

## Apêndice

```{r dicionario - dados, }
data_dictionary(year = 2010, dataset = "population")
```